### ISSUE TITLE
pub.dev/packages support broken

### ISSUE THREAD

**Issue by vince-de-nice** [vscode-contrib/vscode-versionlens#198]
-versions of packages contained in a pubspec.yaml file (flutter project) doesnt match the real pub.dev packages versions
-when trying to update a package version, the update breaks the line below
before (wrong versions displayed: latest is not 0.5.0)
![image](https://user-images.githubusercontent.com/22635303/82413798-499bff00-9a76-11ea-9e8d-7d8f2fe4f1ad.png)
if trying to update anyway:
![image](https://user-images.githubusercontent.com/22635303/82413960-95e73f00-9a76-11ea-932e-4c635ca28d14.png)

**Comment by pflannery** [comment]
@vince-de-nice I'm guessing your using 0.27.0. 
I think the wrong version is displayed because it probably crashed due to the line break issue and stopped working unless you reload the file. 

There is a new release coming shortly that fixes known issues with pub spec files.
There is an alpha of this new release [here](https://github.com/vscode-contrib/vscode-versionlens/releases/tag/1.0.0-alpha.2)

Hoping to have 1.0.0-preview.1 available in vscode by end of this week

**Comment by pflannery** [comment]
1.0.0 is live now. These issues should be addressed

**Comment by pflannery** [comment]
closing this as the fix was released
