### ISSUE TITLE
Versionlens settings ambiguity

### ISSUE THREAD

**Issue by icleolion** [vscode-contrib/vscode-versionlens#212]
The existence of the ambiguity may rest with my lack of understanding, but I'm struggling to understand how these three settings differ from each other precisely.

![image](https://user-images.githubusercontent.com/47498402/82651403-05defc00-9c14-11ea-91c9-8e52e083b318.png)

**Comment by pflannery** [comment]
Hopefully this makes it a bit clearer.

|property|description|icon|
|-|-|-
|`suggestions.showOnStartup`|Shows release suggestions by default on vscode start up|![image](https://user-images.githubusercontent.com/1727302/82676350-2ae86480-9c3e-11ea-9cbb-09ddba6401db.png)
|`suggestions.showPrereleasesOnStartup`|Shows prerelease suggestions by default on start up (aka tags x.x.x-beta.1)|![image](https://user-images.githubusercontent.com/1727302/82676780-d691b480-9c3e-11ea-860c-23a13725c45b.png)

I will remove the statuses (installed statuses) for now as that functionality (that worked in 0.27.0) isnt enabled yet in >=1.0.0 and may not actually be used very often.

**Comment by pflannery** [comment]
Originally prereleases used to spawn horizontally on some packages thus the icon to show\hide was created

e.g. `no match | latest | x.x.x-final.4 | x.x.x-final.3| x.x.x-final.2| x.x.x-final.1| etc......`

But in the last few versions prereleases have been set it up so that they are rolled up using common prerelease names. 

![image](https://user-images.githubusercontent.com/1727302/82677841-93384580-9c40-11ea-8689-25da9f2dc902.png)


This functionality rolls up the above example in to 

`no match | latest | x.x.x-final.4`

I would like to extend the common names in to the configuration too so that people can roll up names not listed in the code.

**Comment by icleolion** [comment]
> Hopefully this makes it a bit clearer.
> 
> `suggestions.showOnStartup`	Shows release suggestions by default on vscode start up
> `suggestions.showPrereleasesOnStartup`	Shows prerelease suggestions by default on start up (aka tags x.x.x-beta.1)


Yep, having just those two, with those descriptions clears it up nicely thanks!

**Comment by pflannery** [comment]
this will be in the next version. closing this

![image](https://user-images.githubusercontent.com/1727302/82681305-810cd600-9c45-11ea-93db-036cbaa3da5f.png)
