### ISSUE TITLE
Incorrect & inconsistent version shown

### ISSUE THREAD

**Issue by rcoundon** [vscode-contrib/vscode-versionlens#219]
WIth Version Lens 1.0.1 (installed via VSIX)

For the buefy dependency in the attached GIF you can see that Version Lens shows latest to be 1.0.0 - however that version is not valid for buefy.  When hovering the current version, the correct latest version is shown and therefore contradicts what is shown before hovering.

![incorrect-version](https://user-images.githubusercontent.com/9136570/82724570-ef49ab00-9cce-11ea-9e1a-cefe430cee3e.gif)

**Comment by rcoundon** [comment]
Love this extension, BTW, use it every day, thanks for your efforts!

**Comment by rcoundon** [comment]
I've learned from the current author that the first author of buefy released a 1.0.0 a long time ago.  Then the versioning system changed and it went to a 0.x.x approach.
So I guess, the checks for the current version isn't taking into account the release dates?

**Comment by pflannery** [comment]
Ah yeah that sucks

I will make a fix that ensures that the latest suggestion always uses the latest tagged version entry for npm.

Technically it's still available and fullfils the pecking order correctly.
Using published dates to determine the latest will conflict with newer patches for previous versions so I want to try to avoid using published dates.

At the moment entering 'latest' does show the correct version that the author tagged as 'latest' but (its still suggesting v1.0.0 wrong in the picture below).

![image](https://user-images.githubusercontent.com/1727302/82728541-d221d600-9ce8-11ea-8895-b8717bc3b513.png)

The author can unpublish v1.0.0. Maybe depreacte

`npm view bueify versions`

```json
[
  "0.0.4",        "0.1.0",        "0.1.1",  "0.1.2",
  "0.1.3",        "0.1.4",        "0.1.5",  "0.2.0",
  "0.2.1",        "0.2.2",        "0.3.0",  "0.3.1",
  "0.3.2",        "0.4.0",        "0.4.1",  "0.4.2",
  "0.4.3",        "0.4.4",        "0.4.5",  "0.4.6",
  "0.5.0",        "0.5.1",        "0.5.2",  "0.5.3",
  "0.5.4",        "0.6.0",        "0.6.1",  "0.6.2",
  "0.6.3",        "0.6.4",        "0.6.5",  "0.6.6",
  "0.6.7-beta.0", "0.6.7-beta.1", "0.6.7",  "0.7.0",
  "0.7.1",        "0.7.2",        "0.7.3",  "0.7.4",
  "0.7.5",        "0.7.6",        "0.7.7",  "0.7.8",
  "0.7.9",        "0.7.10",       "0.8.0",  "0.8.1",
  "0.8.2",        "0.8.3",        "0.8.4",  "0.8.5",
  "0.8.6",        "0.8.7",        "0.8.8",  "0.8.9",
  "0.8.10",       "0.8.11",       "0.8.12", "0.8.13",
  "0.8.14",       "0.8.15",       "0.8.16", "0.8.17",
  "0.8.18",       "0.8.19",       "1.0.0"
]
```

**Comment by snebjorn** [comment]
I also encountered this

![image](https://user-images.githubusercontent.com/1266245/82798069-522a7600-9e78-11ea-8a56-725d491df85c.png)

**Comment by icleolion** [comment]
@snebjorn That package doesn't use a semver compliant versioning system (https://github.com/OpenAPITools/openapi-generator-cli/issues/14), Version Lens shows 0.0.6 as the latest because this was the last version released that was semver compliant.

So your issue is different to @rcoundon and I would suggest is actually more closely related to mine (https://github.com/vscode-contrib/vscode-versionlens/issues/214), whereby I think we both want the behaviour to be if the package doesn't use a semver compliant version then just return the latest version number based on date released on the right side of the pipe, and on the left side just return "not semver compliant" or similiar.

**Comment by pflannery** [comment]
@snebjorn

The following quote is from https://docs.npmjs.com/cli/dist-tag#purpose

> Typically, projects only use the latest tag for stable release versions, and use other tags for unstable versions such as prereleases.

The author in this case has published a prerelease in to the latest tag. 
This clashes with the actual latest release 0.0.6. (v0.0.6 being an initial development version)

I will have to experiment with just forcing the latest suggestion to be the latest tagged version regardless of latest release (for npm only). That is how the initial development prototype of versionlens did it (I believe).

@icleolion 
> That package doesn't use a semver compliant versioning system

[Prerelase examples from semver 2.0.0 spec ->](https://semver.org/#spec-item-9) Examples: 1.0.0-alpha, 1.0.0-alpha.1, **1.0.0-0.3.7**, 1.0.0-x.7.z.92.

It looks valid unless my eyes are deceiving me. It's unusual to see that kind of prerelease format though.

**Comment by icleolion** [comment]
@pflannery I don't think these are prereleases, as per the issue (https://github.com/OpenAPITools/openapi-generator-cli/issues/14) I linked, they seem to be fusing together two seperate version numbers, which is why I didn't see this as being valid semver.

**Comment by snebjorn** [comment]
@pflannery prior versions of VersionLens suggested the correct non-semver versions. At least in the _latest_ version section. I can understand why it wouldn't know what to do in the _satisfies_ section, but that's on the OpenApiTools team :)

**Comment by pflannery** [comment]
I think you've misread what I said. 

Im saying that `1.0.13-4.3.1` is a **valid** semver version. `1.0.13-4.3.1` is in prerelease format as per spec.

If you turn on tagged versions then you can see the prerelease is suggested as expected

![image](https://user-images.githubusercontent.com/1727302/82827265-8f0d6180-9ea6-11ea-9211-f4670f8c324f.png)

![image](https://user-images.githubusercontent.com/1727302/82828073-38a12280-9ea8-11ea-8d12-1be72f374e1a.png)

**I think I've got a good solution**. 

I want to tread carefully about offering prereleases as the 'latest' release suggestion because people are religous about releases and prereleases. Suggestions are also a common API between providers.

I've added a check that if the latest suggestion is a prerelease then set the text to 'latest prerelease'. 

![image](https://user-images.githubusercontent.com/1727302/82831912-9a19bf00-9eb1-11ea-83f9-755488d26921.png)

![image](https://user-images.githubusercontent.com/1727302/82832140-3348d580-9eb2-11ea-9788-5d280b70774c.png)

I think it indicates what to expect quite nicely without breaking expectations.

**Comment by pflannery** [comment]
the [vsix build artifact for this fix is here](https://github.com/vscode-contrib/vscode-versionlens/actions/runs/114967602) feel free to manually install and try it out; or 
you can wait until I bump to the next version which will probably be in this week (but not to marketplace until publish is fixed).

**Comment by pflannery** [comment]
This fix is in the current release. thanks for reporting everyone.
