### ISSUE TITLE
Private npm packages no longer working

### ISSUE THREAD

**Issue by TimBailey-pnk** [vscode-contrib/vscode-versionlens#243]
Hi, we have some private packages on npm.  Version 0.27 correctly shows package information, >=1.0.0 does not, just tried 1.0.0.6

**Comment by pflannery** [comment]
I found the issue. 

Looks pacote is no longer passing auth through in newer versions.
I have reverted to a version that npm is currenlty using.

Because of the #211 saga I wasn't looking to make a release until the end of the week.

In the meantime there is a [preview build 1.0.7-preview.1](https://github.com/vscode-contrib/vscode-versionlens/releases/tag/1.0.7-preview.1)

**Comment by AlexZeitler** [comment]
> In the meantime there is a [preview build 1.0.7-preview.1](https://github.com/vscode-contrib/vscode-versionlens/releases/tag/1.0.7-preview.1)

Auth works using `1.0.7-preview.1` 👍

**Comment by pflannery** [comment]
1.0.7 is now released so will close. thanks for reporting
