### ISSUE TITLE
What is "not authorized"?

### ISSUE THREAD

**Issue by phonglt7** [vscode-contrib/vscode-versionlens#244]
<img width="718" alt="Screen Shot 2020-05-27 at 10 27 57" src="https://user-images.githubusercontent.com/46190930/82974739-e1649480-a004-11ea-9df7-f463691aaba2.png">

**Comment by pflannery** [comment]
version lens uses [libnpmconfig](https://github.com/npm/libnpmconfig) to obtain the user's npm configuration (.npmrc lookups etc...) and passes that to [npm pacote client](https://github.com/npm/pacote).

A "not authorized" usually occurs (for me) when there is an authentication issue with npm config.

Are you using a private registry? 
is there an .npmrc file in the same path as package.json ?

**Comment by MarkusDeutschmann** [comment]
I have the same problem. It happend since version 1.0.0. So latest version that runs fine reagarding that is version 0.27.0. 
I'm using a own npm server (Verdaccio) but npm still work fine without any issue. 
I never had a .npmrc file next by the package.json but always in the home user directory.
Could it be that the change in version 1.0.0:
"Npm: Replaced the old npm cli api with npm pacote api" causes the issue?
Maybe npm cli API was taking the .npmrc file in user home directory into account but npm pacote API does not?

I have the same problem in a Mac and a Windows environment using node v10.19.* and npm v6.13.4.

**Comment by pflannery** [comment]
I found the issue. 

Looks pacote is no longer passing auth through in newer versions.
I have reverted to a version that npm is currenlty using.

Because of the #211 saga I wasn't looking to make a release until the end of the week.

In the meantime there is a [preview build 1.0.7-preview.1](https://github.com/vscode-contrib/vscode-versionlens/releases/tag/1.0.7-preview.1)

**Comment by MarkusDeutschmann** [comment]
Thanks a lot. Preview [build 1.0.7-preview.1](https://github.com/vscode-contrib/vscode-versionlens/releases/tag/1.0.7-preview.1) is working fine again for me.

**Comment by lauralouiset** [comment]
Preview build 1.0.7-preview.1 works for me as well! thanks!

**Comment by pflannery** [comment]
1.0.7 is now released so will close. thanks for reporting

**Comment by sshmyg** [comment]
In v1.0.8 this bug is backed :(
